str=input("Enter a hexadecimal number")
a=int(str,16)
print("decimal number is %d"%a)
str=input("Enter an octal number")
a=int(str,8)
print("decimal number is %d"%a)
str=input("Enter a binary number")
a=int(str,2)
print("decimal number is %d"%a)
